node_js:
- '0.10'
language: node_js

deploy:
  provider: s3
  access_key_id: AKIAJPSYLXQB75SM44ZA
  secret_access_key:
    secure: LEcg2wsRufW22pwajS1G+fbhNvrou/27GIA3dujoeJ1hoo2tYn0Co22koirYiNKTvONbxxWkz/IVy3y8UbcoQti1VkA2jYwl7WO6EscYStZ2G7z/q8R3ZaakqIEWSV9jKAb8YgVflsnH4khjXZTNVmv8s0C60VCVV49ATAmRjzs=
  bucket: artifacts.numenta.org
  local-dir: "$TRAVIS_BUILD_DIR/coverage"
  upload-dir: numenta/nupic.tools


before_script:
- git branch -v
- git remote show origin
- git remote -v

# after_success:
# - test "${TRAVIS_BRANCH}" = "master" && travis_retry gem install travis-artifacts
#   > /dev/null
# - test "${TRAVIS_BRANCH}" = "master" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
#   travis-artifacts upload --path coverage --target-path artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_ID}/${TRAVIS_JOB_ID}
# - test "${TRAVIS_BRANCH}" = "master" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
#   travis-artifacts upload --path coverage/summary.txt --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
#   && echo "Coverage report available at https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_ID}/${TRAVIS_JOB_ID}/lcov-report/index.html"
