node_js:
- '0.10'
language: node_js

deploy:
  provider: s3
  region: us-west-2
  bucket: artifacts.numenta.org
  access_key_id: 
    secure: "jE4/wiSOVZtFuZaOoJITl6SdpLt3tdBiisSpKG3yJ7a5YGlgFdOepjILuiPdtGt0JDHGTv4+d8Kufi7hEJNhJ97irsxyUZ/QWsn8lv31nokOU6CTyT9eyttrvbYeR/qJFvjLYtNJMwqeDZWgWM+X1YvooD8SOz69f9mQCS0vRM0="
  secret_access_key:
    secure: dkAeqwMV3vnKB6MUAg4X+4qNAA/UICsHoTu4uSFTcZSxvftjy8S6oRmGJlVFTTqMciKCGYbN+SQLuAKo3U2E0mkoQ7gA1Uynqfu0h5vKB0LtvP3Que3F58t6PU/LLpIVcXHkVlt/PyTEo+10w79BnY/iilNOqJvYSdxfQhHPpqQ=
  local-dir: "$TRAVIS_BUILD_DIR/coverage"
  upload-dir: numenta/nupic.tools
  skip_cleanup: true


before_script:
- git branch -v
- git remote show origin
- git remote -v

# after_success:
# - test "${TRAVIS_BRANCH}" = "master" && travis_retry gem install travis-artifacts
#   > /dev/null
# - test "${TRAVIS_BRANCH}" = "master" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
#   travis-artifacts upload --path coverage --target-path artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_ID}/${TRAVIS_JOB_ID}
# - test "${TRAVIS_BRANCH}" = "master" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
#   travis-artifacts upload --path coverage/summary.txt --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
#   && echo "Coverage report available at https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_ID}/${TRAVIS_JOB_ID}/lcov-report/index.html"
