--- 
language: node_js
node_js: 
- "0.10"
- "0.11"

env: 
  global: 
  - ARTIFACTS_AWS_REGION=us-west-2
  - ARTIFACTS_S3_BUCKET=artifacts.numenta.org
  - secure: |-
      HO+e7xtHYXsffjQF9Rl2xPHzzjTrGevJvrPwNIYHUfYXxg7t+df0fWJvLsAw
      2LscVgLW0SfABWWHLeFiNmlXEDX38BKPiXpfP2hk9bKt518aSznh8Ghfjv5c
      nK5Nn3Bwsk6Is1W5AtLOnwYkJnCO8wBXus407oLLviC1IdlMDZg=
  - secure: |-
      bQP6qx0abCx9kB4pnXday6BwtrQbyTvcYJbio4EMsvk3vEXSu5ron1IpeP1I
      rjsNAox5/THW63sNMTAqem+0fYFBhlze3CxV3EbGD/aBz2C7alzEhhEnbQ/v
      gzqa02skTGytE5xbYb2+l8kc6Pijfwd6GhQux3Ex3kzUNlzKuBw=

before_script: 
- git branch -v
- git remote show origin
- git remote -v
- gem install travis-artifacts
after_script: 
- travis-artifacts upload --path coverage --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID
- travis-artifacts upload --path coverage/summary.txt --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
- echo "Coverage report available at https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID/lcov-report/index.html"
