--- 
node_js: 
- "0.10"
language: node_js

env: 
  global: 
    - ARTIFACTS_AWS_REGION=us-west-2
    - ARTIFACTS_S3_BUCKET=artifacts.numenta.org

    # ARTIFACTS_AWS_ACCESS_KEY_ID
    - secure: |-
        LryXoMT+lhDYreY0xYVBZg0HbpZHik6fUh8ZqCiOoUYrCAkoMck1NWkvWMst
        di3ZnAyQKxnOzqNpWDiBufJnA4OXzm4SnkDj5NT2ZYZ56jRNFXveRD9bmXcz
        PFtP88dQvesy1el66EBBGTfuPls4pI7+Juu9iaK5jo9pup22rX0=

    # ARTIFACTS_AWS_SECRET_ACCESS_KEY
    - secure: |-
        ZDEgrBeE7f9yTjD3Va4uvkEakNcNKTgNTJ8VWT9QUZdmEvlgvGWRvCbUZHQc
        P+tJ/UVBATmEx5RHf0NqKFyfkC/VeA8C3D4ekCnbB11WF/4i8CCGCrhui9Mx
        cfgr20Rz8KuuC/TZklPjVCy+0dXS3o2CL7u2b7XDGYzBYPxayjU=

before_script: 
    - git branch -v
    - git remote show origin
    - git remote -v

after_success: 
    # Install required ruby gem for artifact uploads to S3.
    - test "${TRAVIS_BRANCH}" = "master" && gem install travis-artifacts
    # Publish complete coverage report to S3.
    - test "${TRAVIS_BRANCH}" = "master" && travis-artifacts upload --path coverage --target-path artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_ID}/${TRAVIS_JOB_ID}
    # Publish the coverage summary master branch for comparison in later builds to S3.
    - test "${TRAVIS_BRANCH}" = "master" && travis-artifacts upload --path coverage/summary.txt --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH && echo "Coverage report available at https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_ID}/${TRAVIS_JOB_ID}/lcov-report/index.html"
