node_js:
- '0.10'
language: node_js

deploy:
  provider: s3
  region: us-west-2
  bucket: artifacts.numenta.org
  access_key_id: AKIAJPSYLXQB75SM44ZA
  secret_access_key:
    secure: SUmUe0g8sNceeWIZiMMFp7aHgV7C+SapcefcLVHmV7pWVv5XPXboYI/9AK55vNIVHhHRZQgQQxGmY41O3xXvGCzsN3D6u1QswwZ1POMZmHVe0tqMEOeGD+p2TfoTX1hipOsLxwUR6j5BSf2p2WHy7FaYVW0Nn+rT1ctYrvviT9U=
  local-dir: "$TRAVIS_BUILD_DIR/coverage"
  upload-dir: numenta/nupic.tools
  skip_cleanup: true


before_script:
- git branch -v
- git remote show origin
- git remote -v

# after_success:
# - test "${TRAVIS_BRANCH}" = "master" && travis_retry gem install travis-artifacts
#   > /dev/null
# - test "${TRAVIS_BRANCH}" = "master" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
#   travis-artifacts upload --path coverage --target-path artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_ID}/${TRAVIS_JOB_ID}
# - test "${TRAVIS_BRANCH}" = "master" && test "${TRAVIS_PULL_REQUEST}" = "false" &&
#   travis-artifacts upload --path coverage/summary.txt --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
#   && echo "Coverage report available at https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/artifacts/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_ID}/${TRAVIS_JOB_ID}/lcov-report/index.html"
