node_js:
- '0.10'
language: node_js

deploy:
  provider: s3
  access_key_id: AKIAIGHYSEHV3WFKOWNQ
  secret_access_key:
    secure: Pl6eK+F64KW7I59oHnssRDvb5qca8BE3ad2JRHt01BWF1V/Pf0JV2X2pZfGAHaDQR+vf6rnHB6anD2+MV1d5YaybsaLJ/WT/QB04elx79P0U5HMURzypYwJHsDPdn7ckH3y4v5G3XxrGO/RqWt5YvF6IJR3m+CRtjhJaHT3CJzc=
  bucket: artifacts.numenta.org
  region: us-west-2
  local-dir: coverage
  upload-dir: numenta/nupic.tools
  skip_cleanup: true

before_script:
- git branch -v
- git remote show origin
- git remote -v
