node_js:
- '0.10'
language: node_js

env:
  global:
    # Setting these because they are required for tests to pass.
    - export GH_USERNAME=someuser
    - export GH_PASSWORD=somepass
    - export POSTMARK_API_TOKEN="server_key"

before_script:
- git branch -v
- git remote show origin
- git remote -v
