--- 
after_script: 
- travis-artifacts upload --path coverage --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID
- travis-artifacts upload --path coverage/summary.txt --target-path artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
- echo "Coverage report available at https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID/lcov-report/index.html"
env: 
  global: 
  - ARTIFACTS_AWS_REGION=us-west-2
  - ARTIFACTS_S3_BUCKET=artifacts.numenta.org
  - secure: |-
      CJdye71QR+eexESMCd9FsEYB+7IGXkAoIZrJPALAMYhLoPixx5zm4FAFaazX
      vkBQORndufd5b3FTPswQ8Mzwo1epK0gh2H8f/uQzjSJOHa6FufYkpEuoz4wE
      W9eMAH+vxxsPIta2vA6Vyf4faouHZ+A1Bwou3y/EbEl7Rl5sK8g=
  - secure: |-
      lwl7bFPU6dIGWLJfDbnna3OQveRJOhbHKpL58XB3ld2qHQqpTWyYHyMaYHIe
      7ZP7GMJ/lPZyQOq9yWw6/lGEYT6TWEzgTxXH3wV6K+6zTkiCxno0aXMXk4f2
      Z8XjidLTydaxypFf3S05StGkmsb6e7dkvxOcu18khTP1dvV3Gd8=
node_js: 
- "0.10"
- "0.11"
before_script: 
- git branch -v
- git remote show origin
- git remote -v
- gem install travis-artifacts
language: node_js
