---
  # Where this application will be hosted
  host: "issues.numenta.org"
  port: 8081

  # Location of the directory where logs will be written.
  logDirectory: "logs"
  # Default log level.
  logLevel: "debug"

  # Individual configurations for repositories that will be monitored
  # by this nupic.tools instance.
  #
  # contributors: URL to CSV file containing a list of people who've
  #               signed Numenta's contributor license. This is used
  #               for validating pull requests, ensuring the author
  #               has signed our license.
  #
  # hooks: Paths to local scripts that are executed within a shell
  #        when the key event occurs.
  #   - push: Occurs when code is pushed to `master` branch of the
  #           specified repository.
  #   - build: Occurs on successfull build of the `master` branch of
  #           specified repository.
  #
  # validators: Extra directives for handling validations for
  #             specififed repository.
  #   - exclude: List of validator names that whould not be executed
  #             for this repository.
  monitors:

    numenta/nupic:
      contributors: "http://numenta.org/resources/contributors.csv"
      hooks: 
        push: "~/nupic.tools/bin/post_nupic_push.sh"
        build: "~/nupic.tools/bin/post_nupic_build.sh"

    numenta/nupic.core:
      contributors: "http://numenta.org/resources/contributors.csv"
      hooks: 
        push: "bin/post_nupic.core_push.sh"

    numenta/nupic.tools:
      contributors: "http://numenta.org/resources/contributors.csv"

    numenta/nupic.wallboard:
      contributors: "http://numenta.org/resources/contributors.csv"
      validators: 
        exclude: 
          - "Travis Validator"

    numenta/pycept:
      contributors: "http://numenta.org/resources/contributors.csv"

    numenta/nupic.fluent:
      contributors: "http://numenta.org/resources/contributors.csv"

    numenta/nupic.fluent.server:
      contributors: "http://numenta.org/resources/contributors.csv"
      validators: 
        exclude: 
          - "Travis Validator"

    numenta/NAB:
      contributors: "http://numenta.org/resources/contributors.csv"
      validators: 
        exclude: 
          - "Travis Validator"

    numenta/nupic.cerebro2:
      contributors: "http://numenta.org/resources/contributors.csv"
      validators: 
        exclude: 
          - "Travis Validator"

    numenta/nupic.cerebro2.server:
      contributors: "http://numenta.org/resources/contributors.csv"
      validators: 
        exclude: 
          - "Travis Validator"

    numenta/nupic.geospatial:
      contributors: "http://numenta.org/resources/contributors.csv"

    numenta/numenta.org:
      contributors: "http://numenta.org/resources/contributors.csv"

    numenta/experiments:
      contributors: "http://numenta.org/resources/contributors.csv"

  # Global validator exclusions.
  validators:
    exclude: 
      - "Fast-Forward Validator"

  # Details about each of our mailing lists.
  mailinglists:
    - 
      name: "NuPIC General"
      rosterUrl: "http://lists.numenta.org/mailman/roster/nupic_lists.numenta.org"
      archiveUrl: "http://lists.numenta.org/pipermail/nupic_lists.numenta.org/"
      startmonth: 5
      startyear: 2013
    - 
      name: "NuPIC Hackers"
      rosterUrl: "http://lists.numenta.org/mailman/roster/nupic-hackers_lists.numenta.org"
      archiveUrl: "http://lists.numenta.org/pipermail/nupic-hackers_lists.numenta.org/"
      startmonth: 11
      startyear: 2013
    - 
      name: "NuPIC Theory"
      rosterUrl: "http://lists.numenta.org/mailman/roster/nupic-theory_lists.numenta.org"
      archiveUrl: "http://lists.numenta.org/pipermail/nupic-theory_lists.numenta.org/"
      startmonth: 3
      startyear: 2014
